# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/exynos7870-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/exynos7870-common/proprietary/etc/somxreg.conf:system/etc/somxreg.conf \
    vendor/samsung/exynos7870-common/proprietary/lib/libExynosOMX_Core.so:system/lib/libExynosOMX_Core.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libExynosOMX_Resourcemanager.so:system/lib/libExynosOMX_Resourcemanager.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libarac.so:system/lib/libarac.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsavsac.so:system/lib/libsavsac.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsavscmn.so:system/lib/libsavscmn.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsavsff.so:system/lib/libsavsff.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsavsmeta.so:system/lib/libsavsmeta.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsavsvc.so:system/lib/libsavsvc.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsnaace.so:system/lib/libsnaace.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsnamrnb.so:system/lib/libsnamrnb.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsnamrwb.so:system/lib/libsnamrwb.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomx263dsw.so:system/lib/libsomx263dsw.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomx264dsw.so:system/lib/libsomx264dsw.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxaacd.so:system/lib/libsomxaacd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxaace.so:system/lib/libsomxaace.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxadpcmd.so:system/lib/libsomxadpcmd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxamrd.so:system/lib/libsomxamrd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxevrcd.so:system/lib/libsomxevrcd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxevrce.so:system/lib/libsomxevrce.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxflacd.so:system/lib/libsomxflacd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxhevcdsw.so:system/lib/libsomxhevcdsw.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxmp3d.so:system/lib/libsomxmp3d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxmp43d.so:system/lib/libsomxmp43d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxmp4vdsw.so:system/lib/libsomxmp4vdsw.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxnaace.so:system/lib/libsomxnaace.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxqcelpd.so:system/lib/libsomxqcelpd.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxqcelpe.so:system/lib/libsomxqcelpe.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxsr263d.so:system/lib/libsomxsr263d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxvc1dsw.so:system/lib/libsomxvc1dsw.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxvp8d.so:system/lib/libsomxvp8d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxwmad.so:system/lib/libsomxwmad.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxwmv7d.so:system/lib/libsomxwmv7d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libsomxwmv8d.so:system/lib/libsomxwmv8d.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.AVC.Decoder.so:system/lib/omx/libOMX.Exynos.AVC.Decoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.AVC.Encoder.so:system/lib/omx/libOMX.Exynos.AVC.Encoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Decoder.so:system/lib/omx/libOMX.Exynos.HEVC.Decoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.HEVC.Encoder.so:system/lib/omx/libOMX.Exynos.HEVC.Encoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Decoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Decoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.MPEG4.Encoder.so:system/lib/omx/libOMX.Exynos.MPEG4.Encoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.VP8.Decoder.so:system/lib/omx/libOMX.Exynos.VP8.Decoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.VP8.Encoder.so:system/lib/omx/libOMX.Exynos.VP8.Encoder.so \
    vendor/samsung/exynos7870-common/proprietary/lib/omx/libOMX.Exynos.WMV.Decoder.so:system/lib/omx/libOMX.Exynos.WMV.Decoder.so \
    vendor/samsung/exynos7870-common/proprietary/vendor/lib/egl/libGLES_mali.so:system/vendor/lib/egl/libGLES_mali.so

# Create Mali links for Vulkan and OpenCL
PRODUCT_PACKAGES += libGLES_mali
