# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/exynos7870-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/exynos7870-common/proprietary/lib/hw/gralloc.exynos5.so:system/lib/hw/gralloc.exynos5.so \
    vendor/samsung/exynos7870-common/proprietary/lib/hw/hwcomposer.exynos5.so:system/lib/hw/hwcomposer.exynos5.so \
    vendor/samsung/exynos7870-common/proprietary/lib/hw/keystore.default.so:system/lib/hw/keystore.default.so \
    vendor/samsung/exynos7870-common/proprietary/lib/hw/memtrack.exynos5.so:system/lib/hw/memtrack.exynos5.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libcsc.so:system/lib/libcsc.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libexynosdisplay.so:system/lib/libexynosdisplay.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libexynosgscaler.so:system/lib/libexynosgscaler.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libexynosscaler.so:system/lib/libexynosscaler.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libexynosutils.so:system/lib/libexynosutils.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libexynosv4l2.so:system/lib/libexynosv4l2.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libfimg.so:system/lib/libfimg.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libhwcutils.so:system/lib/libhwcutils.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libhwjpeg.so:system/lib/libhwjpeg.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libion_exynos.so:system/lib/libion_exynos.so \
    vendor/samsung/exynos7870-common/proprietary/lib/libmpp.so:system/lib/libmpp.so
