# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/on7xelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/on7xelte/proprietary/vendor/app/FFFFFFFF000000000000000000000001.drbin:system/vendor/app/FFFFFFFF000000000000000000000001.drbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin:system/vendor/app/mcRegistry/ffffffffd0000000000000000000000a.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin:system/vendor/app/mcRegistry/ffffffffd00000000000000000000016.tlbin \
    vendor/samsung/on7xelte/proprietary/vendor/bin/gpsd:system/vendor/bin/gpsd \
    vendor/samsung/on7xelte/proprietary/vendor/bin/mcDriverDaemon:system/vendor/bin/mcDriverDaemon \
    vendor/samsung/on7xelte/proprietary/vendor/bin/prepare_param.sh:system/vendor/bin/prepare_param.sh \
    vendor/samsung/on7xelte/proprietary/vendor/etc/ca.pem:system/vendor/etc/ca.pem \
    vendor/samsung/on7xelte/proprietary/vendor/etc/plmn_delta.bin:system/vendor/etc/plmn_delta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/plmn_se13.bin:system/vendor/etc/plmn_se13.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/srm.bin:system/vendor/etc/srm.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_apsta.bin:system/vendor/etc/wifi/bcmdhd_apsta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_mfg.bin:system/vendor/etc/wifi/bcmdhd_mfg.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/bcmdhd_sta.bin:system/vendor/etc/wifi/bcmdhd_sta.bin \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/cred.conf:system/vendor/etc/wifi/cred.conf \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/nvram_mfg.txt:system/vendor/etc/wifi/nvram_mfg.txt \
    vendor/samsung/on7xelte/proprietary/vendor/etc/wifi/nvram_net.txt:system/vendor/etc/wifi/nvram_net.txt \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/camera.vendor.universal7870.so:system/vendor/lib/hw/camera.vendor.universal7870.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/gps.default.so:system/vendor/lib/hw/gps.default.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/gralloc.exynos5.so:system/vendor/lib/hw/gralloc.exynos5.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/sensors.universal7870.so:system/vendor/lib/hw/sensors.universal7870.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libHpr_RecFace_dl_v1.0.so:system/vendor/lib/libHpr_RecFace_dl_v1.0.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libHpr_RecGAE_cvFeature_v1.0.so:system/vendor/lib/libHpr_RecGAE_cvFeature_v1.0.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so:system/vendor/lib/libHpr_TaskFaceClustering_hierarchical_v1.0.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libaudio-ril.so:system/vendor/lib/libaudio-ril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libbauthserver.so:system/vendor/lib/libbauthserver.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libbauthtzcommon.so:system/vendor/lib/libbauthtzcommon.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libcsc.so:system/vendor/lib/libcsc.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libegis_fp_normal_sensor_test.so:system/vendor/lib/libegis_fp_normal_sensor_test.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynoscamera.so:system/vendor/lib/libexynoscamera.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynoscamera3.so:system/vendor/lib/libexynoscamera3.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynosgscaler.so:system/vendor/lib/libexynosgscaler.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynosscaler.so:system/vendor/lib/libexynosscaler.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynosutils.so:system/vendor/lib/libexynosutils.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libexynosv4l2.so:system/vendor/lib/libexynosv4l2.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libfloatingfeature.so:system/vendor/lib/libfloatingfeature.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libhwjpeg.so:system/vendor/lib/libhwjpeg.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libprotobuf-cpp-N.so:system/vendor/lib/libprotobuf-cpp-N.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libprotobuf-cpp-fooo.so:system/vendor/lib/libprotobuf-cpp-fooo.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libreference-ril.so:system/vendor/lib/libreference-ril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/librilutils.so:system/vendor/lib/librilutils.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsec-ril-dsds.so:system/vendor/lib/libsec-ril-dsds.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsec-ril.so:system/vendor/lib/libsec-ril.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libseccameracore.so:system/vendor/lib/libseccameracore.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsecnativefeature.so:system/vendor/lib/libsecnativefeature.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsecril-client.so:system/vendor/lib/libsecril-client.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsensorlistener.so:system/vendor/lib/libsensorlistener.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsensorservice.so:system/vendor/lib/libsensorservice.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libstainkiller.so:system/vendor/lib/libstainkiller.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsynaFpSensorTestNwd.so:system/vendor/lib/libsynaFpSensorTestNwd.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libuniplugin.so:system/vendor/lib/libuniplugin.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libwrappergps.so:system/vendor/lib/libwrappergps.so \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/bcm43438A1_V0062.0267.hcd:system/vendor/firmware/bcm43438A1_V0062.0267.hcd \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/bcm4343A0_V0071.0262.hcd:system/vendor/firmware/bcm4343A0_V0071.0262.hcd \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/fimc_is_lib.bin:system/vendor/firmware/fimc_is_lib.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/mfc_fw.bin:system/vendor/firmware/mfc_fw.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/setfile_4h5yc.bin:system/vendor/firmware/setfile_4h5yc.bin \
    vendor/samsung/on7xelte/proprietary/vendor/firmware/setfile_imx258.bin:system/vendor/firmware/setfile_imx258.bin \
    vendor/samsung/on7xelte/proprietary/vendor/lib/hw/flp.default.so:system/vendor/lib/hw/flp.default.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libHpr_LocFace_mvfd_v1.0.so:system/vendor/lib/libHpr_LocFace_mvfd_v1.0.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so:system/vendor/lib/libHpr_LocLandmark_sdm_v1.0.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libMcClient.so:system/vendor/lib/libMcClient.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libMcRegistry.so:system/vendor/lib/libMcRegistry.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libOpenCv.so:system/vendor/lib/libOpenCv.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libSEF.so:system/vendor/lib/libSEF.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libbt-vendor.so:system/vendor/lib/libbt-vendor.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libflp.so:system/vendor/lib/libflp.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/libsomp.so:system/vendor/lib/libsomp.so \
    vendor/samsung/on7xelte/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so
